---
- name: Get Raspberry Pi Specs
  hosts: raspberrypis
  tasks:
    - name: Get CPU Specs
      command: lscpu
      register: cpu_specs

    - name: Get MAC Address
      command: cat /sys/class/net/eth0/address
      register: mac_address

    - name: Display Results
      debug:
        msg:
          - "IP Address: {{ ansible_host }}"
          - "Specifications: {{ cpu_specs.stdout }}"
          - "MAC Address: {{ mac_address.stdout }}"
